#!/bin/sh
### BEGIN INIT INFO
# Provides:          conservify-startup
# Required-Start:    reset_lgw mountvirtfs $local_fs $networking
# Required-Stop:     $local_fs
# Should-Start:
# Should-Stop:
# Default-Start:     02 2 3 4 5
# Default-Stop:      71 0 1 6
# Short-Description:
# Description:
#
#
### END INIT INFO

function do_start {
	if [ ! -f /var/lib/postgresql/data/pg_hba.conf ]; then
		/usr/bin/postgresql-setup initdb

		sed -i 's/ident/md5/g' /var/lib/postgresql/data/pg_hba.conf

		/etc/init.d/postgresql-server start

		for a in /etc/conservify-schema/postgres/*; do
			sudo -u postgres psql -f $a
		done

		for a in /etc/conservify-schema/chirpstack_as/*; do
			psql "postgres://chirpstack_as:password@127.0.0.1/chirpstack_as?sslmode=disable" -f $a
		done

		for a in /etc/conservify-schema/chirpstack_as_data/*; do
			psql "postgres://chirpstack_as_data:password@127.0.0.1/chirpstack_as_data?sslmode=disable" -f $a
		done

		for a in /etc/conservify-schema/chirpstack_ns/*; do
			psql "postgres://chirpstack_ns:password@127.0.0.1/chirpstack_ns?sslmode=disable" -f $a
		done
	fi
}

case "$1" in
	"start")
		do_start
		;;
esac
