#!/bin/sh
### BEGIN INIT INFO
# Provides:          conservify-startup
# Required-Start:    reset_lgw mountvirtfs $local_fs $networking
# Required-Stop:     $local_fs
# Should-Start:
# Should-Stop:
# Default-Start:     02 2 3 4 5
# Default-Stop:      71 0 1 6
# Short-Description:
# Description:
#
#
### END INIT INFO

function apply_migrations {
	dir="$1"
	pgurl="$2"

	echo applying migrations in ${dir}

	completed=${dir}/.completed
	mkdir -p ${completed}

	for file in `find ${dir} -maxdepth 1 -type f -iname "*.sql"`; do
		echo applying $file
		sudo -u postgres psql ${pgurl} -f ${file} && mv ${file} ${completed}
	done
}

function do_migrate {
	apply_migrations "/etc/conservify-schema/postgres" ""
	apply_migrations "/etc/conservify-schema/chirpstack_as" "postgres://chirpstack_as:password@127.0.0.1/chirpstack_as?sslmode=disable"
	apply_migrations "/etc/conservify-schema/chirpstack_as_data" "postgres://chirpstack_as_data:password@127.0.0.1/chirpstack_as_data?sslmode=disable"
	apply_migrations "/etc/conservify-schema/chirpstack_ns" "postgres://chirpstack_ns:password@127.0.0.1/chirpstack_ns?sslmode=disable"
}

function do_start {
	if [ ! -f /var/lib/postgresql/data/pg_hba.conf ]; then
		/usr/bin/postgresql-setup initdb

		sed -i 's/ident/md5/g' /var/lib/postgresql/data/pg_hba.conf

		/etc/init.d/postgresql-server start
	fi

	do_migrate

	/opt/conservify/bin/update-gw.sh
}

case "$1" in
	"start")
		do_start
		;;
esac
